### ISSUE TITLE
couldn't to connect to 127.0.0.1:6801

### ISSUE THREAD

**Issue by gotbletu** [zsugabubus/aria2t#2]
how you get it to start?

```
./aria2t
couldn't to connect to 127.0.0.1:6801
```

**Comment by zsugabubus** [comment]
Ah, sorry. Default port should be 6800. I fixed it on master.

**Comment by zsugabubus** [comment]
I put usage instructions at the end of the manual page (`man ./aria2t.1` if you didn't run install yet) and I added it to README too, so it should be on the frontpage now. Hope that will help.

**Comment by gotbletu** [comment]
getting these message now

try#1
```
./aria2t
couldn't to connect to 127.0.0.1:6800
```

try#2
```
env ARIA_RPC_SECRET=mysecret ARIA_RPC_PORT=12345 ./aria2t
couldn't to connect to 127.0.0.1:1234
```

try#3
```
./aria2t.1

./aria2t.1: line 1: .TH: command not found
./aria2t.1: line 2: .SH: command not found
./aria2t.1: line 3: aria2t: command not found
./aria2t.1: line 5: .SH: command not found
./aria2t.1: line 6: .SY: command not found
./aria2t.1: line 8: .SH: command not found
./aria2t.1: line 9: .B: command not found
./aria2t.1: line 10: syntax error near unexpected token `('
./aria2t.1: line 10: `is a simple, minimal, low footprint frontend for aria2c(1).'
```

try#4
```
env ARIA_RPC_SECRET=mysecret ARIA_RPC_PORT=12345 ./aria2t.1

./aria2t.1: line 1: .TH: command not found
./aria2t.1: line 2: .SH: command not found
./aria2t.1: line 3: aria2t: command not found
./aria2t.1: line 5: .SH: command not found
./aria2t.1: line 6: .SY: command not found
./aria2t.1: line 8: .SH: command not found
./aria2t.1: line 9: .B: command not found
./aria2t.1: line 10: syntax error near unexpected token `('
./aria2t.1: line 10: `is a simple, minimal, low footprint frontend for aria2c(1).'
```

**Comment by zsugabubus** [comment]
Are you sure that your aria2c server up and RPC enabled? You can run something like this to find out what port it's listening on: `ss -tlnp | grep aria2c`.

> try#3
> try#4

aria2t.1 is the manual page, you can view it using `man ./aria2t.1`.

**Comment by gotbletu** [comment]
oh i see i got to start the server manually before using this program.

the manpage it has a option to shutdown the server with **F9** but not a way to start a server?

**Comment by zsugabubus** [comment]
Yup.

How could it start, and what setting should it use? Server could be on another host too, on the other side of the world.

**Comment by gotbletu** [comment]
maybe have a hotkey to start the daemon with the current user, if you are not connecting to an existing server/remote server.

this is mainly what i use to start the aria2 daemon manually
https://github.com/baskerville/diana/blob/master/dad

**Comment by zsugabubus** [comment]
> maybe have a hotkey to start the daemon with the current user, if you are not connecting to an existing server/remote server.

And what options should it use to start? You use that script, another one uses another one.
Couldn't you start explicitly the aria2 instance you want then start this interface? You can write a two-line shell script if you want to save that additional one command.

**Comment by zsugabubus** [comment]
If you are still interested, I did some improvements in the `devel` branch. Among others, you run a custom executable on any key, so for example <kbd>C</kbd> executes `~/.config/aria2t/actions/C`. You just put your server starting stuff there and press <kbd>C</kbd>. `aria2t` tries connecting in every 5 seconds. (If you do not want to wait that much press <kbd>CTRL-L</kbd>.)

**Comment by gotbletu** [comment]
Thanks that works perfect.

P.S maybe add some screenshots of the program to the front page
