### ISSUE TITLE
purge current selected item?

### ISSUE THREAD

**Issue by gotbletu** [zsugabubus/aria2t#5]
seems like D/Del only removes from the list.

add a way to purge file (remove/delete item from computer)?

**Comment by zsugabubus** [comment]
I use an external script for this purpose: [aria2.py](https://gist.github.com/zsugabubus/a531e72135182df98faecb3373e3e8f4). Copy it to `~/.config/aria2t/actions` and make it executable.

```sh
cd ~/.config/aria2t/actions
# Create keybinding so aria2t will find it and execute the proper command inside the Python script. 
ln -s aria2.py D
# ln -s aria2.py m
```

**Comment by gotbletu** [comment]
finally gave it a try, works ok, seem like it only works on unfinished/paused downloads.
The finished one, i would have to manually go delete those in my file manager. kind of annoy on those tiny .torrent files

Thanks for the other stuff also, 
m = mpv and o = file manager

P.S would of been better to not rely on python3, since this is a minimal program =)

**Comment by zsugabubus** [comment]
If you are interested, you can play with something like this to automatically clean up unused files (use with care):

```sh
cd path/to/download/dir
{
  # Remove extra Torrent files not in session file.
  {
    zcat session.gz | grep -x '\S.*\.torrent' &&
    find -name '*.torrent'
  } | sort | uniq -u

  # Remove extra .aria2 files with no matching downloaded file.
  find -maxdepth 1 -name '*.aria2' -printf '%P\n' |
  while read f; do
    test -e "${f%.aria2}" || printf "%s\n" "$f"
  done
} | xargs -d '\n' -rtx echo rm
```

> P.S would of been better to not rely on python3, since this is a minimal program =)

For a script (or maybe for the whole program) I think you will not find any better than Python. xmlrpc is in the stdlib so there are no random dependencies. At the end of the day I just want things to work.
